### ISSUE TITLE
Test Suite not working

### ISSUE THREAD

**Issue by Lukeghenco** [learn-co-curriculum/angular-controlleras-lab#3]
The steps to install karma are not listed on this lab, and we are not taught how to install them until the testing controllers lab. Maybe add the instructions:

$ sudo npm install -g karma-cli
$ npm install karma --save-dev
$ npm install jasmine-core --save-dev
$ npm install karma-spec-reporter --save-dev
$ npm install karma-jasmine --save-dev
$ npm install karma-chrome-launcher --save-dev

so that students know how to get the test suite to function.

**Comment by AnnJohn** [comment]
Hi @Lukeghenco sorry about this. We'll look at this right away.

**Comment by AnnJohn** [comment]
hi @Lukeghenco did you run 'learn'? that should automatically install karma. 

We'll update the lab with those instructions but wanted to check to see if that worked for you. Thanks.

**Comment by Lukeghenco** [comment]
No, that didn’t work. I started using npm install, and that was grabbing stuff from a json file with the npm commands.

**Comment by joshrowley** [comment]
Hey @Lukeghenco , i'm one of the devs here at Learn, I'll reach out to you on the Slack channel about this. The learn gem should auto install that stuff for you.
